
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: hyungyu
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # spring 영속성 context 를 service / repository 까지만 유지하게 설정 (warning 방지용)
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: hyungyu
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # spring 영속성 context 를 service / repository 까지만 유지하게 설정 (warning 방지용)

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: hyungyu
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false # spring 영속성 context 를 service / repository 까지만 유지하게 설정 (warning 방지용)
